const { contextBridge, ipcRenderer } = require('electron')
contextBridge.exposeInMainWorld('mca', {
  start: (secs) => ipcRenderer.invoke('start', secs),
  stop: () => ipcRenderer.invoke('stop'),
  status: () => ipcRenderer.invoke('status'),
  installHelper: () => ipcRenderer.invoke('install-helper'),
  isPro: () => ipcRenderer.invoke('is-pro'),
  version: () => ipcRenderer.invoke('version'),
  upgrade: () => ipcRenderer.invoke('upgrade'),
  activateLicense: (key) => ipcRenderer.invoke('activate-license', key),
  getLowPowerPreference: () => ipcRenderer.invoke('get-low-power-preference'),
  setLowPowerPreference: (enabled) => ipcRenderer.invoke('set-low-power-preference', enabled),
  setBatteryProtect: (enabled) => ipcRenderer.invoke('set-battery-protect', enabled),
  setForceSleep: (enabled) => ipcRenderer.invoke('set-force-sleep', enabled),
  onTick: (fn) => ipcRenderer.on('tick', (_, n) => fn(n)),
  onRestored: (fn) => ipcRenderer.on('restored', () => fn()),
  onHelperNeeded: (fn) => ipcRenderer.on('helper-needed', () => fn()),
  onProStatus: (fn) => ipcRenderer.on('pro-status', (_, p) => fn(p)),
  onLowPowerStatus: (fn) => ipcRenderer.on('low-power-status', (_, p) => fn(p)),
})
